tabs:
  - project:
      display_name : Project
      columns:
        - project.project_core.project_shortname
        - project.project_core.project_title
        - project.project_core.project_description
  - contributors:
      display_name : Contact
      columns:
        - project.contributors.contact_name
        - project.contributors.email
        - project.contributors.phone
        - project.contributors.institution
        - project.contributors.laboratory
        - project.contributors.address
        - project.contributors.country
        - project.project_core.project_shortname
  - donor_organism:
      display_name : Donor
      columns:
        - donor_organism.biomaterial_core.biomaterial_id
        - donor_organism.biomaterial_core.biomaterial_name
        - donor_organism.biomaterial_core.ncbi_taxon_id
        - donor_organism.genus_species.text
        - donor_organism.is_living
        - donor_organism.biological_sex
        - donor_organism.weight
        - donor_organism.weight_unit.text
        - donor_organism.weight_unit.ontology
  - specimen_from_organism:
      display_name : "Specimen from organism"
      columns:
        - specimen_from_organism.biomaterial_core.biomaterial_id
        - specimen_from_organism.biomaterial_core.biomaterial_name
        - specimen_from_organism.biomaterial_core.ncbi_taxon_id
        - donor_organism.biomaterial_core.biomaterial_id
        - specimen_from_organism.genus_species.text
        - specimen_from_organism.organ.text
        - specimen_from_organism.organ.ontology
        - specimen_from_organism.organ_part.text
        - process.process_core.process_id
  - cell_suspension:
      display_name : "Cell suspension"
      columns:
        - cell_suspension.biomaterial_core.biomaterial_id
        - cell_suspension.biomaterial_core.biomaterial_name
        - cell_suspension.biomaterial_core.biomaterial_description
        - cell_suspension.biomaterial_core.ncbi_taxon_id
        - specimen_from_organism.biomaterial_core.biomaterial_id
        - cell_suspension.cell_morphology.cell_size
        - cell_suspension.cell_morphology.cell_size_unit.text
        - cell_suspension.cell_morphology.cell_viability
        - cell_suspension.cell_morphology.cell_viability_method
        - cell_suspension.selected_cell_type
        - cell_suspension.total_estimated_cells
        - dissociation_protocol.protocol_core.protocol_id
        - enrichment_protocol.protocol_core.protocol_id
        - process.deviation_from_protocol
        - process.process_core.process_id
  - dissociation_protocol:
      display_name : "Dissociation protocol"
      columns:
        - dissociation_protocol.protocol_core.protocol_id
        - dissociation_protocol.protocol_core.protocol_name
        - dissociation_protocol.protocol_core.protocol_description
        - dissociation_protocol.protocol_core.publication_doi
        - dissociation_protocol.protocol_core.protocols_io_doi
        - dissociation_protocol.protocol_type.text
        - dissociation_protocol.protocol_type.ontology
  - enrichment_protocol:
      display_name : "Enrichment protocol"
      columns:
        - enrichment_protocol.protocol_core.protocol_id
        - enrichment_protocol.protocol_core.protocol_name
        - enrichment_protocol.protocol_core.protocol_description
        - enrichment_protocol.enrichment_method
        - enrichment_protocol.markers
        - enrichment_protocol.min_size_selected
        - enrichment_protocol.max_size_selected
        - enrichment_protocol.protocol_type.text
        - enrichment_protocol.protocol_type.ontology
  - library_preparation_protocol:
      display_name : "Library preparation protocol"
      columns:
        - library_preparation_protocol.protocol_core.protocol_id
        - library_preparation_protocol.protocol_core.protocol_name
        - library_preparation_protocol.protocol_core.protocol_description
        - library_preparation_protocol.cell_barcode.barcode_read
        - library_preparation_protocol.cell_barcode.barcode_offset
        - library_preparation_protocol.cell_barcode.barcode_length
        - library_preparation_protocol.cell_barcode.white_list_file
        - library_preparation_protocol.input_nucleic_acid_molecule.text
        - library_preparation_protocol.input_nucleic_acid_molecule.ontology
        - library_preparation_protocol.library_construction_approach
        - library_preparation_protocol.library_construction_kit.retail_name
        - library_preparation_protocol.library_construction_kit.catalog_number
        - library_preparation_protocol.library_construction_kit.manufacturer
        - library_preparation_protocol.library_construction_kit.batch_number
        - library_preparation_protocol.library_construction_kit.expiry_date
        - library_preparation_protocol.nucleic_acid_conversion_kit.retail_name
        - library_preparation_protocol.nucleic_acid_conversion_kit.catalog_number
        - library_preparation_protocol.nucleic_acid_conversion_kit.manufacturer
        - library_preparation_protocol.nucleic_acid_conversion_kit.batch_number
        - library_preparation_protocol.nucleic_acid_conversion_kit.expiry_date
        - library_preparation_protocol.end_bias
        - library_preparation_protocol.primer
        - library_preparation_protocol.strand
        - library_preparation_protocol.spike_in_kit.retail_name
        - library_preparation_protocol.spike_in_kit.catalog_number
        - library_preparation_protocol.spike_in_kit.manufacturer
        - library_preparation_protocol.spike_in_kit.batch_number
        - library_preparation_protocol.spike_in_kit.expiry_date
        - library_preparation_protocol.spike_in_dilution
        - library_preparation_protocol.umi_barcode.barcode_read
        - library_preparation_protocol.umi_barcode.barcode_offset
        - library_preparation_protocol.umi_barcode.barcode_length
        - library_preparation_protocol.umi_barcode.white_list_file
        - library_preparation_protocol.protocol_core.document
        - library_preparation_protocol.protocol_type.text
        - library_preparation_protocol.protocol_type.ontology
  - sequencing_protocol:
      display_name : "Sequencing protocol"
      columns:
        - sequencing_protocol.protocol_core.protocol_id
        - sequencing_protocol.protocol_core.protocol_name
        - sequencing_protocol.protocol_core.protocol_description
        - sequencing_protocol.instrument_manufacturer_model.text
        - sequencing_protocol.instrument_manufacturer_model.ontology
        - sequencing_protocol.local_machine_name
        - sequencing_protocol.paired_ends
        - sequencing_protocol.protocol_type.text
        - sequencing_protocol.protocol_core.document
        - sequencing_protocol.protocol_type.text
        - sequencing_protocol.protocol_type.ontology
  - sequence_file:
      display_name : "Sequence files"
      columns:
        - sequence_file.file_core.file_name
        - sequence_file.file_core.file_format
        - sequence_file.file_core.checksum
        - sequence_file.read_index
        - sequence_file.lane_index
        - sequence_file.read_length
        - sequence_file.insdc_run
        - cell_suspension.biomaterial_core.biomaterial_id
        - library_preparation_protocol.protocol_core.protocol_id
        - sequencing_protocol.protocol_core.protocol_id
        - process.deviation_from_protocol
        - process.process_core.process_id